// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RosBilRP.Models;

[Table("Ansat")]
public partial class Ansat
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Navn { get; set; }

    public int Telefon { get; set; }
}