// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RosBilRP.Models;

public partial class RosBilDBContext : DbContext
{
    public RosBilDBContext()
    {
    }

    public RosBilDBContext(DbContextOptions<RosBilDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ansat> Ansats { get; set; }

    public virtual DbSet<Bil> Bils { get; set; }

    public virtual DbSet<Kunde> Kundes { get; set; }

    public virtual DbSet<Leje> Lejes { get; set; }

    public virtual DbSet<Opgave> Opgaves { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=RosBilDB;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Ansat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ansat__3214EC07C32AD702");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Bil>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bil__3214EC078EE6EB0D");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Kunde>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Kunde__3214EC07F9E60CD9");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Leje>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Leje__3214EC07E4F91169");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Bil).WithMany(p => p.Lejes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BilId");

            entity.HasOne(d => d.Kunde).WithMany(p => p.Lejes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KundeId");
        });

        modelBuilder.Entity<Opgave>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Opgave__3214EC07E814ED5C");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Ansat).WithMany(p => p.Opgaves)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Opgave__AnsatId__02FC7413");

            entity.HasOne(d => d.Bil).WithMany(p => p.Opgaves)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Opgave__BilId__04E4BC85");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}