// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

[Table("Leje")]
public partial class Leje
{
    [Key]
    public int Id { get; set; }

    public int KundeId { get; set; }

    public int BilId { get; set; }

    public DateOnly Dato { get; set; }

    public int AntalDage { get; set; }

    [ForeignKey("BilId")]
    [InverseProperty("Lejes")]
    public virtual Bil Bil { get; set; }

    [ForeignKey("KundeId")]
    [InverseProperty("Lejes")]
    public virtual Kunde Kunde { get; set; }
}